import namesEn from "./playerNamesEn.json";
import type { Team, Player } from "./types";

// Team names in Supabase end with the 3-letter club code, e.g. "上海虎鲸棒球俱乐部SHO".
function teamCode(team: Team): string {
  return team.name.match(/([A-Z]{3})$/)?.[1] ?? "";
}

// The English names come from src/lib/playerNamesEn.json (regenerated by
// data/cpb_official/sync_english_names.py). Empty string when unknown.
export function englishTeamName(team: Team): string {
  return (namesEn.teams as Record<string, string>)[teamCode(team)] ?? "";
}

export function englishPlayerName(team: Team, player: Player): string {
  return (namesEn.players as Record<string, string>)[`${teamCode(team)}-${parseInt(player.number, 10)}`] ?? "";
}
