import namesEn from "./playerNamesEn.json";
import type { Team, Player } from "./types";

// Team names in Supabase end with the 3-letter club code, e.g. "上海虎鲸棒球俱乐部SHO".
function teamCode(team: Team): string {
  return team.name.match(/([A-Z]{3})$/)?.[1] ?? "";
}

// The English names come from src/lib/playerNamesEn.json (regenerated by
// data/cpb_official/sync_english_names.py). Empty string when unknown.
export function englishTeamName(team: Team): string {
  return (namesEn.teams as Record<string, string>)[teamCode(team)] ?? "";
}

// The name is spelled as in the league's 40-man list; `family` is the stretch of it the
// official site prints in bold (the family name), absent when it can't be told. A hand-fixed
// entry may list several stretches, e.g. ["Urrutia", "Henry"] for "U. Henry".
export interface EnglishNameParts { name: string; family?: string | string[] }

export function englishPlayerParts(team: Team, player: Player): EnglishNameParts | null {
  const key = `${teamCode(team)}-${parseInt(player.number, 10)}`;
  return (namesEn.players as Record<string, EnglishNameParts>)[key] ?? null;
}

// "Chen Guan Xun" — plain text (file names, dropdown options, search). "" when unknown.
export function englishPlayerName(team: Team, player: Player): string {
  return englishPlayerParts(team, player)?.name ?? "";
}

// "陈冠勋 Chen Guan Xun" — Chinese name followed by the English one (left out when unknown).
export function bilingualName(team: Team, player: Player): string {
  const en = englishPlayerName(team, player);
  return `${player.name || (en ? "" : "?")}${player.name && en ? " " : ""}${en}`;
}
