import namesEn from "./playerNamesEn.json";
import type { Team, Player } from "./types";

// Team names in Supabase end with the 3-letter club code, e.g. "上海虎鲸棒球俱乐部SHO".
function teamCode(team: Team): string {
  return team.name.match(/([A-Z]{3})$/)?.[1] ?? "";
}

// The English names come from src/lib/playerNamesEn.json (regenerated by
// data/cpb_official/sync_english_names.py). Empty string when unknown.
export function englishTeamName(team: Team): string {
  return (namesEn.teams as Record<string, string>)[teamCode(team)] ?? "";
}

// Spelled like the official site: family name first (the site prints it in bold), then the given names.
export interface EnglishNameParts { family: string; given: string }

export function englishPlayerParts(team: Team, player: Player): EnglishNameParts | null {
  const key = `${teamCode(team)}-${parseInt(player.number, 10)}`;
  return (namesEn.players as Record<string, EnglishNameParts>)[key] ?? null;
}

// "Chen Guan-Xun" — plain text (file names, dropdown options, search). "" when unknown.
export function englishPlayerName(team: Team, player: Player): string {
  const p = englishPlayerParts(team, player);
  return p ? `${p.family} ${p.given}`.trim() : "";
}

// "陈冠勋 Chen Guan-Xun" — Chinese name followed by the English one (left out when unknown).
export function bilingualName(team: Team, player: Player): string {
  const en = englishPlayerName(team, player);
  return `${player.name || (en ? "" : "?")}${player.name && en ? " " : ""}${en}`;
}
